AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  PortalAccountId:
    Type: String

  TeamAdminRoleName:
    Type: String
    Default: Team-Admin-Role
    Description: Name of the Team Admin IAM Role

  TeamPowerUserRoleName:
    Type: String
    Default: Team-Power-User-Role
    Description: Name of the Team Power User IAM Role

  TeamViewOnlyRoleName:
    Type: String
    Default: Team-View-Only-Role
    Description: Name of the Team Power User IAM Role

  TeamName:
    Type: String
    Default: TeamAlpha

Resources:

  TeamAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref TeamAdminRoleName
      AssumeRolePolicyDocument:
        !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:iam::${PortalAccountId}:role/Team-Portal-Role"
                },
                "Action": "sts:AssumeRole",
                "Condition": {
                  "StringEquals": {
                    "aws:PrincipalTag/TeamAdmin": "True",
                    "aws:PrincipalTag/${TeamName}": "True"
                  }
                }
              }
            ]
          }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: CF-Stack-Name
          Value: !Ref AWS::StackName

  TeamPowerUserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref TeamPowerUserRoleName
      AssumeRolePolicyDocument:
        !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:iam::${PortalAccountId}:role/Team-Portal-Role"
                },
                "Action": "sts:AssumeRole",
                "Condition": {
                  "StringEquals": {
                    "aws:PrincipalTag/TeamAdmin": "True",
                    "aws:PrincipalTag/${TeamName}": "True"
                  }
                }
              },
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:iam::${PortalAccountId}:role/Team-Portal-Role"
                },
                "Action": "sts:AssumeRole",
                "Condition": {
                  "StringEquals": {
                    "aws:PrincipalTag/TeamPowerUser": "True",
                    "aws:PrincipalTag/${TeamName}": "True"
                  }
                }
              }
            ]
          }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      Tags:
        - Key: CF-Stack-Name
          Value: !Ref AWS::StackName

  TeamViewerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref TeamViewOnlyRoleName
      AssumeRolePolicyDocument:
        !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:iam::${PortalAccountId}:role/Team-Portal-Role"
                },
                "Action": "sts:AssumeRole",
                "Condition": {
                  "StringEquals": {
                    "aws:PrincipalTag/${TeamName}": "True"
                  }
                }
              }
            ]
          }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      Tags:
        - Key: CF-Stack-Name
          Value: !Ref AWS::StackName
